image: alpine/edge
packages:
  - go
sources:
  - https://github.com/go-ap/storage-fs
secrets:
  - 4f3f5b78-ec70-4a96-a7e4-ea522d87da52
environment:
  GO111MODULE: 'on'
tasks:
  - tests: |
      cd storage-fs
      make test
  - coverage: |
      cd storage-fs
      git switch -C master origin/master
      make coverage
      go run github.com/mattn/goveralls@latest -flagname unit-tests -service=${CI_NAME} -coverprofile storage-fs.coverprofile -repotokenfile ~/.coveralls.tok
