image: alpine/edge
packages:
  - go
sources:
  - https://github.com/go-ap/storage-fs
secrets:
  - 4f3f5b78-ec70-4a96-a7e4-ea522d87da52
environment:
  GO111MODULE: 'on'
tasks:
  - tests: |
      cd storage-fs && make test
  - conformance-suite: |
      cd storage-fs
      go test -tags conformance -count=1 -json . | go run github.com/gotesttools/gotestfmt/v2/cmd/gotestfmt -showteststatus
  - coverage: |
      set -a +x
      cd storage-fs && make coverage
      go run github.com/mattn/goveralls@latest -flagname unit-tests -coverprofile=storage-fs.coverprofile -service=sourcehut -repotokenfile ~/.coveralls.tok
